name = "LeanW26"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanW26"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.26.0-rc2"

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso.git"
rev = "main"

[[lean_lib]]
name = "LeanW26"


